### ISSUE TITLE
All items respawn when loading a savegame

### ISSUE THREAD

**Issue by FreddoUK** [viti95/FastDoom#10]
I think I found a bug, if you collect some items, then save, then load that save, the items you collected will of respawned. This seems to include health vials, armour shards, ammunition, even key cards.

I tested with 0.66 and 0.666, on doom 1 and 2 (full versions).

**Comment by viti95** [comment]
FastDoom 0.7 will include this bugfix 😄 . Thanks @FreddoUK !!
