### ISSUE TITLE
Desync in Ultimate Doom DEMO4

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#100]
Since FastDoom version 0.6 there is a desync in DEMO4 of the Ultimate-doom.
The first jump to the right platform fails when it should not.

In FastDOOM 0.5 the problem did not occur.

**Comment by RamonUnch** [comment]
With 0.6 the visible desync starts whith the jump and with 0.7 the desync starts even earlyer with one of the two shotgunners being hit by an Imp projectile and missed by the player. So I guess more work will be needed. I will start investigating 0.5-0.6 regression first.

**Comment by RamonUnch** [comment]
between 387ce1c (OK) and 3329d70 (not OK), so the culprit is 3329d70 
With build 3329d70 I get early desync with shotgunner. like with latest 0.8.16

**Comment by RamonUnch** [comment]
When thinking about it `lastlook` is set at a random value between 0 and 3 in `P_SpawnMobj`, then in `P_LookForPlayers` the stop value is set at this random value minus 1; so there is indeed something that happens here, I will try to fix this for the latest build.

**Comment by viti95** [comment]
Tested and working perfectly fine. Performance impact should be pretty much none.
