### ISSUE TITLE
Small bug about lost souls and more about demo compatibility

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#102]
After being able with the latest test build to play back ep4-342.lmp, I tried to playback to play back Zero-Master's ep4-331.lmp I did saw a desync in e4m5 just after a lost soul was shot. Took me a lot of testing to find out why...

Actually it was due to a small mistake when the exe were unified in d4d42e9. The problem is at line 266-272 of p_mobj.c were you deleted the `#if (EXE_VERSION < EXE_VERSION_ULTIMATE)` and not the associated code, at the same time you were mostly making the exe mostly Ultimate-Doom compatible.

So I would suggest you remove the lines here:
https://github.com/viti95/FastDoom/blob/91803a4493b113776eede435f432f90fcdc9a602/FASTDOOM/p_mobj.c#L266-L271

If I remove those lines, then ep4-331.lmp plays back properly.

But I also suggest that a compatibility mode is added so that people can choose if they want to play in ultimate-doom mode, doom2 mode (no bouncing lost souls and non baron boss can end e1m8, and also a FinalDoom mode where that is like Ultimate with the funny teleporter bug that is so dear to final doom players. and the compatibility mode would apply automatically depending on IWAD.

I understand if you prefer to keep a single compatibility mode but you already have some specific code to handle non-ultimate-doom. so I think it would make sense to support the three game modes.

This would also help with regression testing as if we are able to play a couple of movies for each IWAD then we are sure we did not break any important game logic. So in the long run this will help debugging.

Otherwise We could focus on pure Ultimate-doom demo-compatibility which is almost already the case except (at least) for the small mistake I started the issue with.

**Comment by viti95** [comment]
Yeah you're right, it's a good idea to add compatibility levels to FastDoom, depending on what IWAD has been loaded. I unified all the executables into single one not caring (and not understanding) about the differences between versions. Now I understand a little bit better those differences, so it will be nice to support it.

**Comment by RamonUnch** [comment]
Also commit https://github.com/viti95/FastDoom/commit/5cc4e2bb125cbe9fc1b615bc518f587387824f63 should be reverted.
If I revert it I can playback `ep2-344.lmp` by Zero-Master, otherwise I get a desync in e2m4.

**Comment by RamonUnch** [comment]
Also now with all of the above if I change the lost soul bouncing code for doom2 mode tom I can finally fully play `30uv2030.LMP`
I think we are good now or at least almost.

**Comment by RamonUnch** [comment]
Fix:
[AltSnap1.57test22_x64.zip](https://github.com/viti95/FastDoom/files/9686065/AltSnap1.57test22_x64.zip)
[AltSnap1.57test22_i386.zip](https://github.com/viti95/FastDoom/files/9686067/AltSnap1.57test22_i386.zip)

**Comment by viti95** [comment]
I've added a complevel variable, which depends on what IWAD is loaded to provide better demo compatibility:

- Doom Shareware (1 episode), Doom Registered (3 episodes) and Doom 2 -> Complevel 2
- Ultimate Doom (4 episodes) -> Complevel 3
- Final Doom (TNT + Plutonia) -> Complevel 4

https://github.com/viti95/FastDoom/commit/a64b33983c9b35895d9af07134af2c63916a827e

**Comment by RamonUnch** [comment]
Also the `void A_BossDeath(mobj_t *mo)` function in `p_ennemy.c` should be adjusted I think, It only affects non IWADS maps though.

**Comment by RamonUnch** [comment]
Could there also be a command-line argument to override auto iwad compatibility mode so that demo recorded with DOOM2.EXE for final doom can be played back? Some people did that because joyb_speed 31 trick would not work with final doom exe, then they would `DOOM2.EXE -file TNT.WAD -record ...` also this could be useful if you play a wad made for DOOM but you only got an ultimate-doom IWAD. renaming can work but override flag makes sense, like with chocolate/crispy-doom.

**Comment by viti95** [comment]
That should be easy, i'll add a similar PRBoom+ complevel command line parameter to manually force it.

> Also the `void A_BossDeath(mobj_t *mo)` function in `p_enemy.c` should be adjusted I think, It only affects non IWADS maps though.

What needs to be changed?

**Comment by RamonUnch** [comment]
In DOOM version 1.9, any boss monster death was able to lower 666 tagged sector. In ultimate doom/finalDoom, only barons can lower 666 tagged sector in e1m8. I am no longer sure this function is responsible for this because i do not fully understand it.
in 0.7 you had this:

https://github.com/viti95/FastDoom/blob/4ba8c204f9333f21bd81b3455d2e882e2e9b6704/p_enemy.c#L1582-L1607

In 0.8.16 you have replaced the #if by if (gamemode == commercial) which will never be the case because it is in the else statement of a if with the same state value.

**Comment by RamonUnch** [comment]
This is what the doom wiki says about differences between exe: https://doomwiki.org/wiki/Versions_of_Doom_and_Doom_II#v1.9
I need to make a test wad or to find one.

**Comment by RamonUnch** [comment]
[T666TEST.zip](https://github.com/viti95/FastDoom/files/9691109/T666TEST.zip)
Hers is a simple test wad. in -complevel 2 with prboom when you kill the Cyber or the Baron, the sector lowers.
In complevel 3 when you kill the cyber, nothing happens and you need to kill the baron for the sector to lower.

**Comment by viti95** [comment]
So what do you think is the best solution for this issue??

**Comment by RamonUnch** [comment]
Thanks a lot for all your work, this port is amazing.
