### ISSUE TITLE
Plutonia MAP12 crashes if music is enabled

### ISSUE THREAD

**Issue by viti95** [viti95/FastDoom#113]
It doesn't crash without music enabled

**Comment by viti95** [comment]
FastDoom versions 0.8 to 0.8.16 are correct, only fails 0.9

**Comment by viti95** [comment]
Also I've researched and this error also happened on older ZDoom versions (prior to 2.1.0) and PS3
Doom and got fixed.

**Comment by RamonUnch** [comment]
Interesting indeed, I need to investigate.
By the way with OpenWatcom we supposedly should be able to use a debugger do you have any information on how to do this under DOS?

**Comment by viti95** [comment]
I've tried to debug with OpenWatcom Debugger using a COM port to DosBox [https://www.javiergutierrezchamorro.com/depurar-aplicaciones-dos-con-watcom-c-y-openwatcom-c/](url) but it was extremely unstable and discarded the idea of using it. Instead I develop the i_debug.c functions which allow to write on a secondary display in DosBox (a simulated MDA adapter y conjunction with the VGA). It's not as good as a debugger but better than nothing.

**Comment by Tronix286** [comment]
I am not sure, but something strange is happening around AL_SendOutputToPort function in ns_sbmus.c. And even more precisely in the area of ​​the line
`   outp(port + 1, data);
`
I run wdis -l ns_sbmus.obj and listing look like this:
```
...skip...
00E1  89 CA				mov		edx,ecx     ; outp(port,reg);
00E8  EE				out		dx,al
... skip ...
00F3  8A 04 24				mov		al,[esp]    ; outp(port + 1, data);
00F6  8D 51 01				lea		edx,0x1[ecx] ; <- !!! VERY STRANGE (port+1) calculation? !!!
00FE  EE				out		dx,al

```
So, i simply try to replace outp(port+1,data) to outp((unsigned short)port + 1,data) and listing look like this:
```
...skip...
00E1  89 CA				mov		edx,ecx     ; outp(port,reg);
00E8  EE				out		dx,al
... skip ...
00F3  0F B7 D1				movzx		edx,cx
00F6  8A 04 24				mov		al,[esp]    ; outp(port + 1, data);
00F9  42				inc		edx         ; YEAH, its +1 now
00FF  EE				out		dx,al
```

But MAP12 still crushes. So, i global redifine AL_SendOutputToPort function with unsigned shorts and unsigned char parameters (in ns_sbmus.c and ns_sbmus.h files). It was:
`void AL_SendOutputToPort(int port, int reg, int data)`
It has become:
`void AL_SendOutputToPort(unsigned short port, unsigned char reg, unsigned char data)`

After that no more crushes in MAP12 plutonia....

**Comment by RamonUnch** [comment]
It is strange because it is not solely related to the music, if you do `idmus12` in map01 then you get no crash and if you play another midi from map12 you still get the crash. I tried with the Plutonia midi pack `plutmidi.wad` and I still get the map12 crash in FastDoom v0.9.

**Comment by Tronix286** [comment]
Ah yes, i am going to wrong way with sounds... So i just looked at PS3DOOM sources and found this fix:
```
    // PS3DOOM: This will fix the crash in eg. plutonia.wad map12.
    if (mthing->type <= 0)
        return;
```
if [p_mobj.c](https://github.com/dirsors/ps3doom/blob/b48cf71b5477d5ad09d86e47189ba5d3235a5084/source/p_mobj.c) file. 
I create pull-request: #119

**Comment by RamonUnch** [comment]
I thought this was already merged, this was something I proposed it alongside the mthing NULL check in [#34](https://github.com/viti95/FastDoom/issues/34#issuecomment-1264743624)
But actually when I look at the source it seems it got skipped somehow.

**Comment by viti95** [comment]
@RamonUnch you're right, I missed to add the proper fix, my bad. Huge thanks @Tronix286 for finding it out!
