### ISSUE TITLE
Add -iwad parameter

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#120]
Most source ports support the -iwad parameter to select the desired iwad, it would be convenient to have this in FastDoom, this would prevent the choice menu to show up when using batch files.

**Comment by viti95** [comment]
Very good idea, I'll add it. The question is how Doom ports decide what complevel to use depending on what iwad is used. Maybe they store a small "database" to select correct complevels.

**Comment by RamonUnch** [comment]
I think we could use file name and file sizes to determine original iwads and set default complevel for those. We could limit the list to vanilla iwads.
I think PrBoom does not auto-select complevel based on iwad unless you use the -complevel vanilla in this case it will use 2,3,4 based on the iwad. So for unknow IWADS I guess we can default to -complevel 2? for the rest name + filesize would be nice because DOOM.WAD is often actually the ultimate doom.

For old doom iwads ie: DOOM2.WAD v1.666  also complevel 2 should be safe because it will be the closest to what was used. Of course fastdoom is not designed to use old iwads but it could still happen. So I guess the only needed list is only foe the final versions of the Vanilla IWADS then default to complevel 2.
It is a proposition of course, I am just thinking loudly.
