### ISSUE TITLE
Feature Request: add back networking (As a build flag)

### ISSUE THREAD

**Issue by EndlessEden** [viti95/FastDoom#128]
I know networking was removed to add performance to FastDoom; However, i think simple TCP networking should be returned. 

Full netstack from source is unnecessary, but tcp/ip would help usability greatly.
(EG: return tcp/ip stack, leave out ipx, null-modem, etc)

**Comment by arrowgent** [comment]
ipx to tcp/ip works in dosbox
so you can do server/client within dosbox across the internet or local network

just dosbox, as an example.

**Comment by viti95** [comment]
@arrowgent FastDoom has completely removed networking support, neither IPX nor null modem are supported. And I'm pretty sure it's not going back, since lot's of changes has been made (and optimized) and proved to make Doom much better on slower CPUs such as the 386SX
