### ISSUE TITLE
Adlib FX mode broken since 0.9

### ISSUE THREAD

**Issue by viti95** [viti95/FastDoom#135]
Found by @deathz0r: Adlib FX mode only works in 0.8.15 and 0.8.16 and is broken in 0.9, confirmed with using a reproduction Adlib clone. I suspect that the OPLxLPT pull request (introduced in 0.9) had broke it somehow.

**Comment by jsmolina** [comment]
@viti95 I'm wondering if just adding the opl3lpt option to FX will just also give FX in this device as well.

**Comment by viti95** [comment]
It could work, the Adlib FX mode basically bitbangs the OPL chip in order to produce sound. To test if it works force the variable AL_OPL2LPT or AL_OPL3LPT to TRUE, and set the ADLIB_PORT value to the desired port. I still don't have neither an OPL2LPT nor the OPL3LPT, so I cannot test it myself.

**Comment by viti95** [comment]
@Deathz0r confirmed this issue is fixed now
