### ISSUE TITLE
Intelligent midi via soundblaster gameport (aka SoftMPU)

### ISSUE THREAD

**Issue by neuralnetworkz** [viti95/FastDoom#142]
Hi, since softmpu doesn't work with Fastdoom (afaik)
Maybe there is an option to include it in the soundsystem itself somehow?

The setup I use: soundblaster pro 1.0 with a mt32

**Comment by neuralnetworkz** [comment]
Ok will try. Will be able to in a few weeks.

**Comment by viti95** [comment]
Newest 0.9.6 release supports SB-MIDI for pre SB16 sound cards, so I proceed to close this issue.
