### ISSUE TITLE
Wrong fps display if 0XX after decimal point.

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#145]
ie: 1710 gametics * 35 / 136 rticks = 440.073 fps
FastDoom displays 440.73 fps which is wrong.

Just replace the `FPS: %u.%u` by `FPS: %u.%.3u` and the output will be zero padded after the dot and everything will be fine.

**Comment by viti95** [comment]
Yeah it was not working properly. Will do a bugfix release due to this. Thanks for discovering this issue!!
