### ISSUE TITLE
Computer hangs at W_Init

### ISSUE THREAD

**Issue by txjacob** [viti95/FastDoom#149]
I've tried launching fdoom, but I cannot get past the startup screen. I get
```
FastDoom version 0.9.6
P_Init: Checking cmd-line parameters...
M_LoadDefaults: Load system defaults.
Z_Init: Init zone memory allocation daemon.
DPMI memory: 6232 Kb, 5848 Kb allocated for zone
W_Init: Init WADfiles.
        adding doom.wad
```
and the whole system seems to freeze. I'm running a 486DX.

**Comment by viti95** [comment]
I need a bit more of information. Are you using version 1.9 of doom.wad? Also, is the doom.wad the 3 episode release or is a different one? Can you provide information of the OS / hardware setup used? 

Thanks!

**Comment by viti95** [comment]
Also can you try the newest FastDoom release?

Thanks!

**Comment by txjacob** [comment]
Hey viti95, turns out I was using the wrong file as the wad, getting one from archive.org fixed it immediately.

**Comment by viti95** [comment]
Great, I hope you're enjoying it :D
