### ISSUE TITLE
No Sound Blaster sound since at least v0.9.4

### ISSUE THREAD

**Issue by SpitFire-666** [viti95/FastDoom#157]
Been a while since I've fired up my rig...

Unfortunately I can't get sound blaster sound FX working on the more recent FastDOOM versions, including v0.9.8. I ended up going down the rabbit hole, testing v0.94, 95, 96 and 97 - none of which worked with sound.

I tested stock Doom which worked just fine - with these settings:

```
Card		Port	IRQ	DMA channel	Channels
Sound Blaster	220	5	1		3
```

Finally reverted to **v0.8.14 which worked just fine** - by setting the sound card to the same settings as above.

If you need any details let me know. My audio card is an ESS something or other. Cheers!

**Comment by dougvj** [comment]
I couldn't reproduce this, I even have an ensoniq chip on one of my machines that seemed to work fine

 Can you provide more information on your hardware info?

**Comment by SpitFire-666** [comment]
Thanks @dougvj not sure what my card is called exactly as it has 2 chips, an ES688 and a ES968. 

![image](https://github.com/viti95/FastDoom/assets/38451588/411a4f64-e7d6-44d2-b5aa-c60cd080503a)

Pic of another I found: 

https://i.ebayimg.com/images/g/juIAAOSw2LhkCuKo/s-l1600.jpg

**Comment by viti95** [comment]
Additionally, could you please provide details about your system specifications and BLASTER settings?

**Comment by dougvj** [comment]
I looked through my collection and I sadly do not have this card. I found one on eBay that is on the cusp of affordability I might pick it up.

**Comment by SpitFire-666** [comment]
> Additionally, could you please provide details about your system specifications and BLASTER settings?

Sure. Toshiba T5200, 13MB RAM, Paradise VGA card (built-in, 256k), TEXAS INSTRUMENTS TX486DLC/E-40GA 40 MHz PGA-132 CPU. 

I use [UNISOUND ](https://www.vogons.org/viewtopic.php?f=62&t=72553) to magically configure the sound card in DOS. Dunno how it works or if it even sets a BLASTER variable.

**Comment by viti95** [comment]
Oh I also had one Toshiba T5200, but it died years ago 😔. Loved the orange plasma display, mine came with a 386DX at 20MHz.

It's possible to see the BLASTER variable with this command line: **ECHO %BLASTER%** after Unisound configures everything

**Comment by SpitFire-666** [comment]
OK solved! There was no BLASTER var set. Tested FDOOM .9.8 and we're all good, cheers!
