### ISSUE TITLE
Quick question about converting music for PCM mode

### ISSUE THREAD

**Issue by Ethaniel-404** [viti95/FastDoom#177]
I have SoX ready and the Sycraft package with a total of 24 .ogg files. The Readme files shows one conversion example:

_sox D_E1M1.ogg -r 44100 -e unsigned -b 8 -c 1 MUS_1.RAW_

My question is: What's the naming pattern for the rest of the files? I assume D_E1M2.ogg, D_E1M3.ogg and D_E1M4.ogg should be called _MUS_2.RAW, MUS_3.RAW and MUS_4.RAW_, but I also have files like _D_E2M1.ogg, D_E3M1.ogg_, and even _d_bunny.ogg or d_intro.ogg_.

Should I just append the «MUS_» at the front and leave the rest intact?

**Comment by viti95** [comment]
The files must be named MUS_1.RAW, MUS_2.RAW and so on. Yet I have to publish which song goes in which position 😅, I'll try to post it this week.

**Comment by viti95** [comment]
Sorry for being really late, I've updated the readme.txt file with the track numbers, also added a wiki entry for this: https://github.com/viti95/FastDoom/wiki/PCM-music-and-Audio%E2%80%90CD-track-numbers
