### ISSUE TITLE
Fastdoom and SoftMPU and awe

### ISSUE THREAD

**Issue by TheElf01** [viti95/FastDoom#181]
Hi!  a small question, i dont know if someone already tested, but fastdoom (last version included) hang when exit if softmpu is loaded, and awe32 music is selected

I tried with emm386 or qemm  same problem.   Dont hang is other music type is selected, Sound blaster, adlib,  PCM, CD, speaker, etc

But softmpu+awe  always hang when exit, never return to dos prompt.  Tested in a Pentium 3 and 486 DX4 machine

Any ideas? love using awe  but i have softmpu loaded always

thanks!

**Comment by viti95** [comment]
[FDOOM_AWE32_SOFTMPU.zip](https://github.com/viti95/FastDoom/files/14899092/FDOOM_AWE32_SOFTMPU.zip)

I've changed a bit how FastDoom terminates the EMU8000 chip, it's working on my AWE32. Can you test if this avoids the crash with SoftMPU? Thanks!

**Comment by TheElf01** [comment]
> [FDOOM_AWE32_SOFTMPU.zip](https://github.com/viti95/FastDoom/files/14899092/FDOOM_AWE32_SOFTMPU.zip)
> 
> I've changed a bit how FastDoom terminates the EMU8000 chip, it's working on my AWE32. Can you test if this avoids the crash with SoftMPU? Thanks!

Ahh esto no es vogons, podemos hablar en español jaja,   te confirmo funciona perfecto este build en mi awe64, ningun cuelge

I confirm works fine!  thanks!

**Comment by viti95** [comment]
Genial que ya funcione bien, para la siguiente release estará disponible . Procedo a cerrar la incidencia  😄
