### ISSUE TITLE
crash on startup for a Pentium 3

### ISSUE THREAD

**Issue by jsmolina** [viti95/FastDoom#187]
![WhatsApp Image 2024-04-05 at 23 50 40](https://github.com/viti95/FastDoom/assets/447481/112d40e7-5e56-4ac2-b060-c6fb8530bb34)
![WhatsApp Image 2024-04-05 at 23 49 51](https://github.com/viti95/FastDoom/assets/447481/ddf66780-6c46-4a25-8749-fd1dc8651860)
my pentium 3 is not able to run latest release (0.9.9b) and also fails on 0.9.9.

In windows 98se: crashes the whole OS
in ms-dos, gives a stack trace (see screenshot)

It happens no matter of sound card configuration.

It works on 0.9.5

**Comment by jsmolina** [comment]
thank you for your great work on this!

**Comment by viti95** [comment]
Curioso, falla justo en cuanto pulsas la selección de menu? o falla antes de llegar a pulsar?

**Comment by jsmolina** [comment]
> Curioso, falla justo en cuanto pulsas la selección de menu? o falla antes de llegar a pulsar?
Sólo tengo doom2.wad, no me da ni la oportunidad a escoger opción que ya peta (con cualquier exe)

**Comment by viti95** [comment]
Cuando puedas envíame la lista de ficheros que tienes en la carpeta raíz, parece que el código de selección de WADs es lo que está fallando.

**Comment by TheElf01** [comment]
> Duda, estáis usando Windows 9x o es MS-DOS 6 puro? Si borrais el fichero fdoom.cfg funciona?

En mi caso,  DOS puro. Mismo error aunque borre el cfg

**Comment by viti95** [comment]
He estado haciendo pruebas con mi P3 550 (Katmai), 128Mb de RAM y una Sound Blaster AWE64, y me ha funcionado bien con el EMM386, tanto con el EMS como sin el (con MS-DOS 6.22). Voy a necesitar mas detalles para ver si podemos apuntar a que está fallando exactamente.

**Comment by TheElf01** [comment]
> He estado haciendo pruebas con mi P3 550 (Katmai), 128Mb de RAM y una Sound Blaster AWE64, y me ha funcionado bien con el EMM386, tanto con el EMS como sin el (con MS-DOS 6.22). Voy a necesitar mas detalles para ver si podemos apuntar a que está fallando exactamente.
> 
> EDIT: he ampliado la RAM hasta 384Mb y también sin problemas

Claro, decime en que puedo ayudarte, encantado

Sobre mi PC

256mb ram
1GHZ P3
VIA chipset
DOS7
1 particion 128GB FAT32

Deje un Config.sys/autoexec simple

DOS=HIGH,UMB
device=himem.sys
device=emm386.exe ram (o noems pasa igual)

en autoexec solo unisound para iniciar el awe64


Ahora, si quito emm386 o uso qemm ningun problema


![IMG_20240403_221121_1](https://github.com/viti95/FastDoom/assets/16392474/ce71d778-a825-49d8-9a4b-53228f2204a2)

**Comment by jsmolina** [comment]
yo sólo 

- he descomprimido la release en una carpeta limpia
- he copiado doom2.wad, versión 1.9.
no hay nada más en la carpeta que eso.
Mi placa: "[MSI MS-6368 Socket 370]", es curioso que también es Chipset VIA. VIA PLE133T
Diría que mi chipset también es VIA

**Comment by jsmolina** [comment]
Nasm simplemente lo he instalado con brew (brew install nasm)
Y watcom he conseguido compilarlo en mi Macbook M1, lo cual me acelera más las pruebas gracias al post: 
https://web.navan.dev/posts/2024-03-15-setting-up-macos-for-8088-dos-dev.html

```
export WATCOM=/path/to/open-watcom-v2/rel
export PATH=$PATH:$WATCOM/armo64
export EDDAT=$WATCOM/eddat

# For DOS 8088/8086 development
export INCLUDE=$WATCOM/h
export LIB=$WATCOM/lib286
``
`

Lo importante, aquí con el doom1 shareware y doom2 full:
![WhatsApp Image 2024-06-02 at 19 39 25 (3)](https://github.com/viti95/FastDoom/assets/447481/a0bec2c3-cf9e-45b5-a5a0-86d356964d5b)

He puesto unos printf para debugar "a lo clásico" (o a lo cutre)
![WhatsApp Image 2024-06-02 at 19 39 25 (2)](https://github.com/viti95/FastDoom/assets/447481/0dfec752-1b1d-4288-9c13-e526e97178b0)

Por los printf, **llega al final de LoadIWAD**, pero entonces hace el Segmentation Fault como ves entre eso y antes de pintar "DOOM 2: Hell on Earth v%i.%"

@viti95 otro día que pueda añado más printf a ver exactamente qué línea peta.

**Comment by viti95** [comment]
Mmmmm por desgracia el depurador nunca he conseguido que funcione de manera estable en OpenWatcom, así que si, la única manera es hacerlo a la vieja usanza 😅

Es cierto que ahora hay varias maneras de hacerlo más sencillo, es posible depurar en una pantalla externa de tipo MDA / Hercules, a través de puerto serie o a través de un fichero de log (este es el que suelo usar yo). Para usarlo tienes que incluir la cabecera "i_debug.h" donde quieras "depurar" y usar el método I_Printf para imprimir. Para compilar tienes que añadir un nuevo parametro para que funcione: **./build.sh fdoom.exe -clean -debug**. Y la configuración de la depuración la tienes en el fichero "dbgcfg.h". A ver si un día me da por editar la wiki y explicar bien esto jaja.

Respecto al fallo que te sucede, lo único que se me ocurre es lo que has hecho, añadir mensajes en la inicialización y ver cuál es el último que llega a ejecutarse.

**Comment by jsmolina** [comment]
He aislado @viti95 el 'pete' a `setbuf(stdout, NULL);` 
Qué curioso porque es algo bastante normal de C.

voy a quitar esa línea y ver qué ocurre...

**Comment by viti95** [comment]
Creo que realmente no cambiaría el resultado, sizeof(char) en Watcom C de 32bits siempre devuelve valor 1. La versión original de la función D_AddFile era esta:

`void D_AddFile (char *file)
{
    int     numwadfiles;
    char    *newfile;
	
    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
	;

    newfile = malloc (strlen(file)+1);
    strcpy (newfile, file);
	
    wadfiles[numwadfiles] = newfile;
}
`

Lo unico que cambia es que en vez de usar el malloc original de C, usamos la version de malloc interna de Doom (Z_Malloc) para tener mayor control de lo que se asigna en memoria.

**Comment by viti95** [comment]
Creo que he encontrado el fallo que te está sucediendo. Básicamente me ha sucedido lo mismo bajo 86Box, con una maquina con una configuración totalmente distinta. ¿En la funcion I_ZoneBase (i_ibm.c), puedes probar a modificar el valor de 

```c
if (!ptr) heap -= 0x400; // try again with 1Kb less
`

por 0x800 o 0x1000 (2kb o 4kb)? Me da la sensación de que alguna función interna de Watcom está intentando reservar memoria al cargar los ficheros, pero al ir tan ajustado (solo deja 1kb libre por defecto) da un fallo dependiendo de los TSR o demás cosas que estén cargadas en el SO.

**Comment by viti95** [comment]
No se porqué el VSCode me ha cerrado automáticamente la issue cuando he subido el commit, la primera vez que veo algo así 😶

**Comment by jsmolina** [comment]
> No se porqué el VSCode me ha cerrado automáticamente la issue cuando he subido el commit, la primera vez que veo algo así 😶


sip, es porque has puesto fixes + número de issue 😄, es del propio github, y bastante útil para evitar dejarte issues abiertas.

**Comment by jsmolina** [comment]
![image](https://github.com/viti95/FastDoom/assets/447481/a0e332c2-ccad-4c0d-b5f7-e6f2e99fe8fb)
creo que sólo retrasa el fallo, ahora no veo mis prints...

**Comment by viti95** [comment]
Genial, con eso ya puedo replicar en mi equipo la incidencia:

![image](https://github.com/viti95/FastDoom/assets/8323882/7ff9babb-eba8-4621-9ee5-7cfb753ae352)

**Comment by jsmolina** [comment]
@viti95 con tu último cambio el juego arranca. Ya sólo una pega pero minor: que no sale el texto que dice que está arrancando jajajaja, pero bueno nada del otro mundo.

**Comment by jsmolina** [comment]
con el último commit va perfecto! he estado jugando un rato a 800x600, con su OPL3 real y suena y se mueve impresionante!

**Comment by jsmolina** [comment]
@TheElf01  prueba este, lo he compilado yo en MacOs , a mí ya no me peta😄 
[fdm600d.zip](https://github.com/user-attachments/files/15810812/fdm600d.zip)
