### ISSUE TITLE
Visual Error on E2M2 Demo/Screen Melt Transition

### ISSUE THREAD

**Issue by ezgoodnight** [viti95/FastDoom#200]
MiSTer FPGA on the ao486core, DOS 6.22

Pretty noticeable visual error happening at the end of the E2M2 demo. Vanilla does not appear to do this.

[fastdoom visual errors.webm](https://github.com/user-attachments/assets/3a445434-acff-489e-8878-a94a52c26232)

I've been able to reproduce it twice, just seems to happen every time the E2M2 demo ends.

**Comment by viti95** [comment]
Can you share FastDoom version and executable used? Also, can you check what Doom WAD version do you have?

**Comment by ezgoodnight** [comment]
FastDoom Latest 0.9.9e

MD5: c4fe9fd920207691a9f493668e0a2083
WAD File: The Ultimate DOOM (v1.9)

**Comment by ezgoodnight** [comment]
I checked this WAD in DosBox X and it crashes Vanilla Doom after E2M2 with the error 

> W_GetNumForName: HELP2 not found!

[I am guessing this link is relevant](https://talk.dengine.net/discussion/1744/missing-patch-help2-doom). Is FastDoom looking for HELP2 and creates this error?

**Comment by ezgoodnight** [comment]
This visual error happens with this same WAD in DOSBox-X as well, so not a MiSTer FPGA issue.
![image](https://github.com/user-attachments/assets/0700afaa-1472-49e6-9e00-aa5ae3f19c82)

**Comment by viti95** [comment]
Question, is the WAD file named DOOM.WAD or DOOMU.WAD ?

**Comment by ezgoodnight** [comment]
Simply "doom.wad"

**Comment by ezgoodnight** [comment]
All versions I just checked, including the commercially available version from GOG, have it labeled as DOOM.WAD despite being Ultimate Doom. I think most people's Ultimate Doom Wads are going to be named with that convention.

I think it would be useful to update the Readme for users to rename their ultimate doom wads as DOOMU.WAD and/or [check their hashes first.](https://github.com/Ch0wW/wadverifier)

Most source ports these days seem let users treat Doom 1 Wads sort of interchangeably, but I can understand your commitment to keeping FastDoom so vanilla.

I can confirm that changing it to DOOMU.WAD does indeed load the first slide again, fixes this particular issue.

**Comment by viti95** [comment]
Good idea on checking the hash first. The only issue that a 386 is slow, so I'll add a check for WAD size and modify the readme, I guess that should be enough. Thanks for testing.
