### ISSUE TITLE
bad WAD size notification with Ultimate Doom

### ISSUE THREAD

**Issue by lukeczek** [viti95/FastDoom#214]
There is some bug with notification with bad size od wad file from Ultimate Doom.
In readme is information the doom.wad should be 12408292 bytes but fdoom expecting 11159840.

best regards 
Lucas

**Comment by viti95** [comment]
The Ultimate Doom WAD should be named doomu.wad instead of doom.wad. That's why it's showing a different file size than expected.

**Comment by lukeczek** [comment]
Thank You very much.
best regards from Poland
Lucas

niedz., 29 wrz 2024 o 04:44 Victor Nieto ***@***.***>
napisał(a):
