### ISSUE TITLE
Use fdoom.cfg instad of default.cfg

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#23]
Fdoom has made some modifications to the config file, I think it would be wiser to save them to a different config file, such as fdoom.cfg so that a user could keep fdoom in the same folder than doom without interferances.

**Comment by RamonUnch** [comment]
also given that savegames files are incompatible it could be nice to name them fdoomsv%d.dsg instead of doomsav%d.dsg

**Comment by viti95** [comment]
This is a good idea, i'll check how the IDSETUP program is built, and maybe create a specific version for FastDoom. Also i'll modify the savegames names.
