### ISSUE TITLE
Save autorun to config file

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#24]
Most settings in fdoom are saved in the config file except this one. 
it is strange given that it was unofficially available on vanilla (I always used joyb_speed 29 in vanilla).
I made my own build with autorun always on but it would be nice to have the setting saved.

**Comment by RamonUnch** [comment]
Also I think using:
`speed = !autorun ^ !gamekeydown[key_speed];`
is beter than 
`speed = autorun  || gamekeydown[key_speed];`
because the Shift should toggle walk/run.

**Comment by viti95** [comment]
Another good idea, I'll check how to implement it better.
