### ISSUE TITLE
Build Instructions Are Out of Date

### ISSUE THREAD

**Issue by bnied** [viti95/FastDoom#29]
Build instructions reference running `make.bat`, which does not exist.

Please update the instructions with the correct steps.

**Comment by viti95** [comment]
Yeah you're right, the build process is getting updated and the readme is obsolete. I'll update it for the next release.

**Comment by bnied** [comment]
Danke!

**Comment by bnied** [comment]
Resolved by https://github.com/viti95/FastDoom/commit/dd7728961f476a8f0eadc9a9ded204395e436d45; I was able to build FastDOOM successfully. Thank you!
