### ISSUE TITLE
Shareware 1.9 IWAD does not display the third episode's title on the episode selection screen.

### ISSUE THREAD

**Issue by viti95** [viti95/FastDoom#3]
Found by MrFlibble (Vogons):

"Playing with the shareware 1.9 IWAD does not display the third episode's title for some reason on the episode selection screen"

**Comment by AXDOOMER** [comment]
This seems to be the issue [1]. This fix should only be there for the Ultimate Doom which has 4 episodes, but if you don't compile with the Ultimate Doom as a target, the game has 3 episodes [2]. 

[1] https://github.com/viti95/FastDoom/blob/master/m_menu.c#L1531
[2] https://github.com/viti95/FastDoom/blob/master/m_menu.c#L271

**Comment by viti95** [comment]
Thanks @AXDOOMER, the hack was causing the problem.
