### ISSUE TITLE
0.8.1 startup lockups when using GM or Sound Canvas music

### ISSUE THREAD

**Issue by appiah4** [viti95/FastDoom#31]
**System:**
Biostar 8433UUD-A
IBM Cx5x86-100@120MHz
Macronix MX86200 2MB
Sound Blaster 16 (A220 I5 D1 H5 P300)
PCMIDI MPU-401 I/O (P330)
2GB Sandisk Ultra CF-IDE
LG 16x DVD-RW

**Bug**
Game sometimes (randomly) locks up at Doomguy screen at startup when General MIDI or Sound Canvas is selected.

**Comment by viti95** [comment]
Have you tried without overclocking? I've recently discovered that my Cyrix 5x86 crashed randomly in-game and also in the main menu, and the fault was that overclock.

**Comment by appiah4** [comment]
Reverting to 100MHz indeed resolved the issue so I guess my overclock was not as stable as I thought after all.  Thank you kindly for looking into this!
