### ISSUE TITLE
Some switches do not work properly in FastDoom 0.8.1

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#32]
I was started playing the 4th episode using FastDoom and I was bugged for some time trying to press the first swithc (SW1GARG). 
Pressing this switch does not change the texture and does not makes the "klong" sound. same problem with SW1CMT and SW1GSTON.

Some other switches works as expected like SW1STRTN and SW1COMP

I did not check systematically all switches textures, but you get the point.

**Comment by viti95** [comment]
I've checked that this happens since I unified all the executables (Doom, Ultimate Doom and Doom 2) onto a single one. I'll fix it for the next release. Thanks!
