### ISSUE TITLE
Compilation Switches

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [viti95/FastDoom#33]
I see you are using:
/omaxet /zp4 /3r /ei /j /zq

Typically I use these ones, which should get a better perfomance.
-oneatx -ohirbk -ol -ol+ -oi -ei -zp8 -3r -fpi -mf -s -ri -zm /fhwe

**Comment by viti95** [comment]
Some of those switches are redundant and some ones aren't needed (the FPU ones). For now i've added /oh and /ol+ and those give a little bit of extra performance (1% approx). Also the difference between /zp4 and /zp8 is nearly zero (tested in a 486DX-50). Thanks!
