### ISSUE TITLE
Ultimate DOOM E4M4 exit bars not lowering properly (v0.8.2)

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#36]
I started an episode 4 run, and I encountered this bug in E4M4:
To exit you are supposed to press two switches (lines 416 and 462) with the 102 action: *S1 Floor Lower to highest floor*.
* Switch L462 Lowers successfully Sector 43 as expected, same for the bars that are in half circle around the exit. However it FAILS to lower Sector 61 for the caco cabinet.

* Switch L416 Lowers successfully Sector 41 as expected, However it FAILS to lower Sector 67 for the other caco cabinet. and also fails to lower the big exit bars, except Sector 64, that lowers as expected. A continuous floor lowering sound is played but the other bars are not moving.

Also in some cases when pressing those switches it seems the klong sound does not come from the switch (not reproducible though).

I am playing with FDOOM.EXE (0.8.2) and using DOSBox 0.74-3.

**Comment by RamonUnch** [comment]
To be more clear, the problem was not present under 0.7 but appeared with 0.8.

**Comment by viti95** [comment]
I've uploaded a new release (0.8.3) with the bugfix for this issue. Can you check if this is working properly? Thanks!

**Comment by RamonUnch** [comment]
Congratulations to have figured this out. I did browse through some code but could not find anything.
The 2 caco in each cabinets are just 48 units apart and are stuck together, this is a bug in the map and caco are also stuck in vanilla. Everything seems fine with 0.8.3.
