### ISSUE TITLE
Resident memory in DOS can prevent fdoom to start

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#37]
I did the test under DOSBox 0.74-3.
If you do:
`> FDOOM -timedemo DEMO1`
then quit with the menu before the demo playback has finished.
Then start `> FDOOM` just by its name and you will see fdoom start then quit immediatly with the message:
`Timed 14 gametics in 15 realtics. FPS: 32.22`
Probably you will get different numbers but you get the idea. I had this problem before but needed some time to reproduce it.

It seems that when quitting via the menu then some memory is not erased and when fdoom starts it must lack some variable initialization that makes him think he is playing a demo when he is not.
It is not a big problem as the solution is to specify the -warp parameter with a map name and everything works fine.

The bug appeared at 0.8.1, and was not present for 0.8.0 (from what I tested)
Probably there is some randomness in this one and it would depend on the DOS version

**Comment by viti95** [comment]
I've uploaded a new release, i've tried to fix this bug by initializing the variables but I wasn't able to replicate the problem. Maybe it will work fine.

**Comment by RamonUnch** [comment]
Fixed for me
