### ISSUE TITLE
[suggestion] 640x480 mode?

### ISSUE THREAD

**Issue by campbellkerr** [viti95/FastDoom#43]
Hi there, I have a 386 with 640x480 VGA display (Toshiba T5200). Like many games/DOS apps, Doom is letterboxed (computer doesn't do "scaling"). 

This is a long shot - do you think it's possible for FastDoom to run in VGA mode/640x480?

Really keen to try fastdoom as vanilla doom is almost playable at postage stamp 🤏settings on the Toshy!

Thanks!

**Comment by viti95** [comment]
It's possible but it will be slow as hell. The 640x480 modes requires all the pixels to be updated per frame (~10Mb/s for 35 fps), and that is way beyond what a 386 can move (in fact, even 320x200 is too much for most ISA video cards). Also there are more problems, the 640x480 mode has only 16 colors, which requires a color conversion from the 256 colors that makes it even slower.

**Comment by campbellkerr** [comment]
Thanks for the info - that's a shame. I wonder if the game could be converted to 16 colours easily? My T5200 plasma display does 16 colours/shades of orange. Perhaps that would squeeze out additional FPS, although I'm likely an edge case. Cheers

**Comment by viti95** [comment]
Maybe you can try the 80x50 text mode, it uses only 16 colors and should be filling all the screen. The resolution may be a bit low, but that it should run well on that 386DX at 20MHz. I'll also add a double height resoultion version of that mode, so it renders at 80x100, which should be very playable even at that resolution.

BTW I had one of those "minimalistic" laptops in the past, now I miss it.
