### ISSUE TITLE
Error "Demo is from a different game version!"

### ISSUE THREAD

**Issue by campbellkerr** [viti95/FastDoom#45]
Apologies if this is user error. Getting this message when trying to run fastdoom.exe. I've dropped fastdoom.exe into my DOOM folder (contains the shareware .wad and game files)

![image](https://user-images.githubusercontent.com/38451588/127478278-4b200228-2447-4709-b26e-9cfde360a4f3.png)

Hopefully I'm just doing something dumb! Thanks

**Comment by viti95** [comment]
What version of FastDoom are you using?

**Comment by campbellkerr** [comment]
Thanks. I'm running latest version (0.8.5). Shareware wad is named DOOM1.WAD

I also attempted a couple FDOOMs with the same result. 

Let me know if a video recording would help? Cheers!

**Comment by campbellkerr** [comment]
[https://youtu.be/h-Qj_iQn7Ms](url)

A picture/video says 1,000 words - hope this is helpful!

**Comment by viti95** [comment]
Can you try to upgrade the Doom Shareware WAD from 1.1 to 1.9? The 1.0 and 1.1 versions are known to have some differences that cause trouble (status bar for example cannot be rendered properly)

**Comment by campbellkerr** [comment]
BINGO! Running v1.9 with fastdoom. Good call. You can close this ticket, cheers 👍
