### ISSUE TITLE
Down arrow doesn't seem to work in gameplay

### ISSUE THREAD

**Issue by campbellkerr** [viti95/FastDoom#50]
Hey there, weird one - I can't seem to go backwards by using the down arrow ⬇.

- Using latest v0.8.7
- Note that it works fine in the menu, just not in gameplay
- All other controls seem to work fine
- NumLock key works for going backwards during gameplay 🤷‍♂️
- I can't be sure if this worked in previous versions of FastDoom
- Vanilla Doom (`doom.exe`) has no such issue
- Also tried `fastdoom.exe` with no parameters, same result
  
Thanks for the `-disabledemo` parameter too, killer feature 💪!

**Comment by viti95** [comment]
You're right it's a nasty bug. Don't know why happens, but seems to happen only in the Mode Y (original) version of FastDoom, the other ones doesn't have this problem (!?!??!!). I'll fix it for the next release.

**Comment by viti95** [comment]
I've updated the latest release (0.8.7) with the bugfix, it should work fine. Can you test it? Thanks!

**Comment by campbellkerr** [comment]
Sorry for the delay - my rig was out of action. Just tested and it's all good! You can close this ticket, cheers!
