### ISSUE TITLE
hr2final.wad MAP32 crashes with some screen sizes

### ISSUE THREAD

**Issue by deat322** [viti95/FastDoom#52]
Hello,

I've been using [hr2final.wad](https://www.doomworld.com/idgames/themes/hr/hr2final) MAP32 as a benchmark for testing various FastDoom v0.8.7 EXEs with the TAS UV-Max demo that is at dsdarchive.com, [h232x423.lmp](https://dsdarchive.com/files/demos/hr2final/13775/h232x423.zip) - I have converted this into a WAD to bypass FastDoom's demo compatibility check, and it plays to completion successfully. I've attached the WAD:

[h232x423.zip](https://github.com/viti95/FastDoom/files/7189619/h232x423.zip)

I have a BAT file that I use for easy checking:

`%1 -nosound -file hr2final.wad h232x423.wad -timedemo demo1`

I've noticed when playing back the demo that it will crash when certain screen sizes/modes are used:

Potato quality with screenblocks <= 8
Low quality with screenblocks <= 4
High quality with screenblocks <= 2 (via editing fdoom.cfg)
FDOOMT1
FDOOMT12

Using the demo WAD with vanilla doom2.exe has no issues, even when setting to low quality and screenblocks to 1. The key difference between vanilla and FastDoom that I can see is that FastDoom does not have a sprite rendering limit, though I can not say if that will have any influence on why FastDoom crashes.

It is easy enough to reproduce without the demo WAD by warping to MAP32 on hr2final.wad with potato quality and screenblocks set to <= 3, it will crash before you can leave the starting sector.

I have tested this on a Super Socket 7 and a Socket 370 motherboard with various CPUs and video cards with no other expansion cards or anything else plugged in except the keyboard, and the results are consistent.

**Comment by viti95** [comment]
Moved to #34
