### ISSUE TITLE
AWE music on CT1920 AWE upgrade cards

### ISSUE THREAD

**Issue by CarlosTex** [viti95/FastDoom#6]
Hi, CarlosTex from VOGONS here. The issue i'm presenting here is not a FastDOOM bug. I use a CT1920 AWE upgrade card with a Orpheus Sound card prototype (Sound Blaster 2 Pro compatible). On the majority of games i can get AWE music from the AWE Upgrade card. Unfortunately there are 3 games i know that for AWE music to play one must have a real Sound Blaster 16 in the system for the AWE Upgrade card to play AWE music. Those games are:

- Raptor: Call of the Shadows
- DOOM
- DOOM 2

There's no technical reason for AWE not playing without a SB16 card, the EMU synth is accessed natively by its HW I/O port (620h is default) so there must be a dependency in the code, some kind of check that won't allow EMU8000 to play if a SB 16 card is not found. 

So i'm just requesting for that dependency to be removed, which would be useful for people who use AWE Upgrade card who use SB or SB Pro 2 or compatibles, allowing them to hear AWE music even if a SB 16 is not present.

This would be an enhancement vs the original executables. If you manage to achieve this, maybe you could go into detail on what was needed to be done, and then maybe with that info i could try to patch Raptor: Call of the Shadows.

**Comment by CarlosTex** [comment]
Ok, i just checked my SET BLASTER, and i had my MPU set wrong there. As soon as i fixed that i now have AWE music with a Sound Blaster Pro 2 card. I checked the original unmodified DOOM2.EXE and with that i don't have AWE music, no matter what i try, so you obviously already fixed something in the code.

Bravo!!

**Comment by viti95** [comment]
FastDoom is using the Apogee Sound System, which is different (and better) than the original DMX library that DOOM, DOOM 2 and Raptor shares. There is no DMX source code available (as it is a licensed product), so it's only possible to patch this problem via reverse engineering. Also the Raptor source code wasn't released, which makes the problem even harder.

I'll look into this and see if it's possible to bypass the BLASTER checks and force the initialization of the sound card.

One important thing that I remember while developing for the AWE is that the sound port must be equal to the Sound Blaster port plus 0x400h (220h + 400h = 620h, 240h + 400h = 640h, and so on). Maybe the DMX library is checking that. This is from the Apogee Sound System:

>    wEMUBaseAddx = Blaster.Emu;
>    if (wEMUBaseAddx <= 0) wEMUBaseAddx = wSBCBaseAddx + 0x400;
>    status = awe32Detect(wEMUBaseAddx);
