### ISSUE TITLE
Consider including full FastDoom version number

### ISSUE THREAD

**Issue by SpitFire-666** [viti95/FastDoom#72]
Just a small thing - I can't find any way to identify the exact FastDoom version number from the downloaded/unzipped files.

For example, this is v0.8.10: 

![image](https://user-images.githubusercontent.com/38451588/162368110-b40b10cb-410e-4cb4-939b-c72af4e034f7.png)

![image](https://user-images.githubusercontent.com/38451588/162368144-17791748-0a8d-4403-8e7c-12980dc1995c.png)

Would be useful to check what version my DOS machine is running and if it's the latest and greatest. Cheers!

**Comment by viti95** [comment]
Releases from now on will include full version number. Thanks @SpitFire-666 !
