### ISSUE TITLE
Lockup when using AWE32

### ISSUE THREAD

**Issue by lavadrop** [viti95/FastDoom#80]
Game locks up when AWE32 music and SB sounds are configured. Main screen freezes after pressing a key and selecting an option. Music continues playing in the background. 

Intel 486 DX2/66 4Mb RAM
Speedstar Pro VLB 1Mb GD5428
SB32PnP

**Comment by viti95** [comment]
Can you share the SET BLASTER variable values? Thanks

**Comment by lavadrop** [comment]
Yeah 
`SET BLASTER=A220 I5 D1 H5 P330 E620 T6`

**Comment by viti95** [comment]
Hi! Can you try with the new release of FastDoom (0.9.1)?
