### ISSUE TITLE
[cga] option palette for 4 color cga

### ISSUE THREAD

**Issue by arrowgent** [viti95/FastDoom#82]
the alternate cga colors

cyan magenta white black

![cga](https://lospec.com/palettes/cga-palette-1-high/og-thumbnail.png)

is there an option for this or would you need to create a palette to fit?

running in dosbox maybe an option for dosbox i can test.  will take a look

![cgadoom](https://i.ytimg.com/vi/MgTtLxBS_l4/hqdefault.jpg)
ive seen this one before

**Comment by arrowgent** [comment]
this one works

` * FDOOMPCP.EXE => FastDoom for Plantronics ColorPlus cards. 320x200 and 16 colors!`

![fdpfp1](https://user-images.githubusercontent.com/57545549/169157616-a9d30314-44f2-4128-b612-c5d6fd9ef9fd.png)

i dont know if its supposed to look like this but in dosbox it sets the colors to the old cga format
**It uses the same Motorola MC6845 display controller as the previous MDA and CGA adapters.**

**Comment by arrowgent** [comment]
EGA and PCP modes required significantly more CPU Cycles to maintain 35fps or really they couldnt even reach 35fps in most scenes.

i was doing basic testing setting dosbox cycles to 32767 as a random baseline

**Comment by viti95** [comment]
The backbuffer conversion to EGA and PCP modes is slow, both have a complex video memory layout and are hard to optimize.

**Comment by viti95** [comment]
FastDoom 0.8.17 will feature this new parameter.
