### ISSUE TITLE
Freeze and no sound with dual soundblaster

### ISSUE THREAD

**Issue by neuralnetworkz** [viti95/FastDoom#87]
Hi, I have two sound cards installed:
-sbpro1.0 with dual opl2 
-sb1.5 with installed cms chips

Set blaster is a220 i5 d1 t2 for the sbpro.

The sb1.5 is Jumpered to a210 i7 and drq off, so both cards won’t have conflicts.

With MBF I get sound and music on the sbpro, with Fastdoom 0.8.14 I get no music and it freezes after trying to play the first (menu) sound effect.
I also tried soundblaster direct with the result of no sound.

machine is a IBM ps1 with a 486dx overdrive processor and 64MB Ram

**Comment by neuralnetworkz** [comment]
Took the sb1.5 out, now have music but it still freezes when playing a sound. 
soundblaster direct crashes the pc when I open the ingame menu.

no sound and just soundblaster music works fine.

**Comment by viti95** [comment]
Found the issue, it will be fixed on the next release. As of now, FastDoom 0.8.13 should work fine.

**Comment by neuralnetworkz** [comment]
It works on the pro now, in soundblaster and soundblaster direct mode. Awesome.

May be of interest:
Interesting thing I found out, I only have sound if I call fdoom from the directory it lives in.

If I call it from another directory I have no sound, but it doesn't crash anymore as with the prior version. (Got my wads in another directory)
