### ISSUE TITLE
Fastdoom crashes on e4m9 and e4m3

### ISSUE THREAD

**Issue by neuralnetworkz** [viti95/FastDoom#92]
After a minute into both maps, it crashes.

Fastdoom 0.8.15 
Fdoom13h.exe -ram

Iwad Doomu.wad 

IBM PS/1 
486-75 
64MB RAM 
Soundblaster Pro1

Savegame available if needed

**Comment by viti95** [comment]
Does this happen on older releases?

**Comment by neuralnetworkz** [comment]
I will check later this week

**Comment by neuralnetworkz** [comment]
I tried Fastdoom 0.8.13 and e4m3 crashes after a few seconds

Fastdoom 0.8.14 crashed with my soundblaster pro, so I disabled sfx 
It also crashes on e4m3 after a few seconds

**Comment by viti95** [comment]
Moved to #34
