### ISSUE TITLE
Add customizable address support for Covox devices

### ISSUE THREAD

**Issue by Dairydian** [viti95/FastDoom#93]
Is there any chance you could add some sort of extra menu or field to manually configure the address of the LPT port when a Covox device is chosen? It seems FastDoom is hardcoded to 378, so we can't use alternative addresses like 3BC, 278, or in my case, a800 and c080 (that's when using PCI cards).

**Comment by viti95** [comment]
Sure, i'll add that option.

**Comment by viti95** [comment]
New release 0.8.16 supports customizing the port for COVOX and Disney Sound Source ports. I have tested with the standard ports (0x3BC, 0x378 and 0x278) and works fine but haven't tested any aditional ports (as I don't have any special hardware that allows to other values). FDSetup program only allows to select the three standard ones as it's not designed to write values in the sound card selection, but it's possible to modify the FDOOM.CFG configuration to set any port you want. The only issue is that you have to convert the hexadecimal value to decimal. For example, if I want to set the LPT port to 0x278, i need to write "snd_sport 632" in the config file. Hope it works fine for you!

**Comment by Dairydian** [comment]
Absolutely perfect so far. Selected Covox from setup, then I converted c080 to dec (49280), added that number to fdoom.cfg, and all the effects work! Thank you!

**Comment by viti95** [comment]
Great!
