### ISSUE TITLE
Stupid optimization about intercepts

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#96]
I was thinking about the intercepts overflow bug in vanilla doom and I thought: Why are the non shootable things even listed? So I modified the `PIT_AddThingIntercepts(mobj_t *thing)` function in fastdoom to first ignore everything that does not have the MF_SHOOTABLE flag and could not find any obvious misbehaving.
```
boolean PIT_AddThingIntercepts(mobj_t *thing)
{
    ... DECLATRATIONS ...
    if (!((thing->flags & MF_SHOOTABLE))) return 1;
    etc...
```
I also made small test map with a ton of health bonuses in a line and sure enough, when I shot on the line I no longer had intercept overflow. Of course intercept overflow is still possible with shootable items, the odds are just slightly reduced because there quickly are many corpses and sometime many stacked items.

Plus in theory the code should run faster. The difference is very small however because it only applies to hitscan shot.

So my question is what could go wrong with this optimization? Do I miss something?

**Comment by viti95** [comment]
I'll take a look, the idea is fine. I know it's possible to shoot and activate switches, but don't know if those are shootable objects or not

**Comment by RamonUnch** [comment]
Shootable switches are linedefs. All shootable things should be marked MF_SHOOTABLE. Dammage checks for this flag as well. Also tracers go through solid objects, unkile projectiles that can be blocked by the bottom of torches. This optimization also does not affect those.

The question is: Is the intercepts list used for anything else than tracers? Maybe for splash dammage? Even here what would it change to remove non shootable objects? From my testing nothing, all ultimate doom and DOOM2 demo plays back normally.

I guess the simpler would be to take the choco-doom source, make this only patch, and try to play back some movie to see if it desyncs.

**Comment by RamonUnch** [comment]
Well I tried with a modified chocolate-doom and I can playback without problems `30uvmax4.lmp` (Radek Pecka) and `30uv2030.LMP` (Looper). So I guess it is safe.
I did also check that there is no intercept overflow when shooting on my test map with this modified exe, to be sure it did build correctly.
