### ISSUE TITLE
Unable to play back a .lmp file

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#98]
When trying to play a demo under DOSBox0.74-3, I get the : "Demo is from a different game version!" message.
Even if the demo was recorded under fastdoom.
When recording under fastdoom demo are saved correctly and can be played back on vanilla doom.

The strange thing is that the internal demo can be played back (when they are lumps in the wad).
Also I tryed to remove the version check from fdoom to see what happens and I get a crash when trying to play a demo file.

So my guess is that the file does not get loaded in memory properly when specified from the command line.
I Actually get the same error when specifying a non existant file.

I am aware that you need to be careful not to specify the .lmp extension when trying to play a demo under vanilla.

**Comment by autumnrain26** [comment]
I second that. Trying to play demo from classicdoom.com/d1demos.htm ,  simply crashes without message.

**Comment by RamonUnch** [comment]
The problem occured between version 0.7 and version 0.8.
I even have an early build of version 0.7 that has the bug, but I lost the source it was build from.
Maybe this? https://github.com/viti95/FastDoom/commit/e53fd37132ef9146a720f61527868197b9211f7c

**Comment by RamonUnch** [comment]
From my quick tests the problem occurred between  9894d5f (OK) and 321b87c  (NOT OK).

**Comment by RamonUnch** [comment]
After some pure dichotomy, I can say that the problem started at commit 321b87c
The previous version be5c870 did playback demo files without problem.

We just have to figure out why

**Comment by viti95** [comment]
Tested and working, huge thanks again for solving this issue!!
